### ISSUE TITLE
Advice for running in a modular application.

### ISSUE THREAD

**Issue by brett-smith** [gluonhq/rich-text-area#255]
I am trying to use Rich Text Area in a modular application on Java 17, but am getting `IllegalAccessError` exceptions at run time.

First of all, I tried using the library from Maven Central. Being as it is not itself modularised, I added the automatic module name `rich.text.area` to my `module-info.java`.  This will give a warning, but allows compilation.

```java
requires rich.text.area; 
```

This results in the following exception.

```
Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessError: class com.gluonhq.richtextarea.RichTextAreaSkin$RichVirtualFlow tried to access method 'void javafx.scene.control.skin.VirtualFlow.rebuildCells()' (com.gluonhq.richtextarea.RichTextAreaSkin$RichVirtualFlow is in module rich.text.area@1.0.1-SNAPSHOT of loader 'app'; javafx.scene.control.skin.VirtualFlow is in module javafx.controls of loader 'app')
	at rich.text.area@1.0.1-SNAPSHOT/com.gluonhq.richtextarea.RichTextAreaSkin$RichVirtualFlow.rebuildCells(RichTextAreaSkin.java:303)
	at rich.text.area@1.0.1-SNAPSHOT/com.gluonhq.richtextarea.RichTextAreaSkin$ParagraphListView.updateLayout(RichTextAreaSkin.java:412)
	at rich.text.area@1.0.1-SNAPSHOT/com.gluonhq.richtextarea.RichTextAreaSkin.refreshTextFlow(RichTextAreaSkin.java:549)
	at rich.text.area@1.0.1-SNAPSHOT/com.gluonhq.richtextarea.RichTextAreaSkin.setup(RichTextAreaSkin.java:535)
	at rich.text.area@1.0.1-SNAPSHOT/com.gluonhq.richtextarea.RichTextAreaSkin.<init>(RichTextAreaSkin.java:469)
	at rich.text.area@1.0.1-SNAPSHOT/com.gluonhq.richtextarea.RichTextArea.createDefaultSkin(RichTextArea.java:293)
	at rich.text.area@1.0.1-SNAPSHOT/com.gluonhq.richtextarea.RichTextArea.createDefaultSkin(RichTextArea.java:69)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9529)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1745)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
	at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
```

I have also tried cloning `rich-text-area` source and adding a `module-info.java` so it is a real module, but this results in much the same error.

The only way I have found so far to progress, is to comment out the method in `RichTextAreaSkin.java` it is complaining about, and the single place that calls this method.

```java
//        @Override
//        protected void rebuildCells() {
//            super.rebuildCells();
//        }
```

and ..

```java
        void updateLayout() {
            // force updateItem call to recalculate backgroundPath positions
//            virtualFlow.rebuildCells();
        }
```

This actually gets me a working rich text area, but presumably it breaks something somewhere!

Can anyone explain exactly what's going on here and if there is any other work around or fix?

**Comment by jperedadnr** [comment]
Try RichTextArea 1.1.0 with `requires com.gluonhq.richtextarea;` in your module descriptor. It should work without any issue accessing VirtualFlow.

**Comment by brett-smith** [comment]
This has fixed it, thanks a lot. Great to see a new release.
