### ISSUE TITLE
java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/rich-text-area#275]
Hard to reproduce, but it happened with a table (therefore there are several layers that apply the same call to evict unused objects):

```
Exception in thread "Timer-1" java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)
        at com.gluonhq.richtextarea.ParagraphTile.evictUnusedObjects(ParagraphTile.java:292)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at com.gluonhq.richtextarea.RichListCell.evictUnusedObjects(RichListCell.java:319)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at com.gluonhq.richtextarea.RichTextAreaSkin$ParagraphListView.evictUnusedObjects(RichTextAreaSkin.java:446)
        at com.gluonhq.richtextarea.SmartTimer$1.run(SmartTimer.java:60)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
```

**Comment by jperedadnr** [comment]
This issue happens because there is a single hashMap in richTextAreaSkin (richTextAreaSkin.getFontCache()), and we call 
`forEach(RichListCell::evictUnusedObjects)` from all present cells, therefore calling from multiple places at once:

```
richTextAreaSkin.getFontCache().values().removeAll(cachedFonts);
```
